[retriever]
type = SimpleIMAPRetriever
server = mail.retriever.test
username = jane.doe@retriever.test
password = secret

[destination]
type = MDA_lmtp
host = /run/dovecot/lmtp
#host = mail.example.test
#port = 24
# Replace remote recipient address so that
# Dovecot delivers to the intended local account:
override = jane.doe@destination.test

[options]
verbose = 2
read_all = false
delete = false
